### ISSUE TITLE
Type inference on fixtures stops working

### ISSUE THREAD

**Issue by agatti** [theY4Kman/pycharm-pytest-imp#2]
Hi there, I've noticed that the plugin (version 0.3.1) seems to block type inference to fully work on Pycharm 2020.3.  I've got a fixture that returns a tuple and despite everything being fully annotated, with the plugin enabled the IDE ignores the type bound to the fixture itself.

Here's an example that should clarify things up a bit:

With the plugin installed but disabled:

![Screenshot 2020-12-07 at 23 02 40](https://user-images.githubusercontent.com/235740/101411145-c2fb2200-38e0-11eb-90c0-69b865d1b497.png)

with the plugin enabled:

![Screenshot 2020-12-07 at 23 03 05](https://user-images.githubusercontent.com/235740/101411185-d4442e80-38e0-11eb-9cf3-be21bb63c9a8.png)

the fixture in question is in the module's own `conftest.py` file, and is function scoped.

Is there anything else I can do on my end to help things out?

**Comment by theY4Kman** [comment]
Hmmm, it's entirely possible the plugin is simply overriding any explicitly-declared annotations. It should not do that :P

**Comment by theY4Kman** [comment]
I fixed this in #3, and published it as version 0.3.2; it should be available within a couple days as Jetbrains approves it.

**Comment by agatti** [comment]
Awesome, I'll check it out as soon as Jetbrains makes it available.  Thanks for the fix!

**Comment by theY4Kman** [comment]
It appears Jetbrains has already approved the change! That's the fastest I've ever seen it happen.

**Comment by agatti** [comment]
Yep, it works just fine - thanks again!
