### ISSUE TITLE
Compatibility with 2021.3 EAP

### ISSUE THREAD

**Issue by scorpp** [theY4Kman/pycharm-pytest-imp#9]
New EAP is out and plugin doesn't work any more

**Comment by theY4Kman** [comment]
Ah, yeah, I've been testing out a fix locally, and forgot I never published it. I ought to be able to push this later tonight, and Jetbrains may have it approved in a day or two

**Comment by theY4Kman** [comment]
Okay, I pushed the [0.5.2 release](https://github.com/theY4Kman/pycharm-pytest-imp/releases/tag/0.5.2). It's awaiting Jetbrains's approval for release in the plugins repository, but in the meantime, it's available in [.zip form from the GH release](https://github.com/theY4Kman/pycharm-pytest-imp/releases/download/0.5.2/pytest.imp-0.5.2.zip), which can be installed manually. They've been pretty good about approval turnaround time lately, though, so it might be available in the plugins repo tomorrow :crossed_fingers:

**Comment by scorpp** [comment]
thank you for the plugin and for quick feedback!

**Comment by scorpp** [comment]
ok, i confirm the updated version is approved now and fixes the issue.
